namespace Sales.Client.Helpers
{
    public enum Strings
    {
        SelectLanguage,
        SiteName,
        Home,
        Login,
        Register,
        Logout,
        Profile,
        Notifications,
        NotFound,
        NotFoundTip,
        NotFoundTip1,
        NotFoundTip2,
        UserName,
        EmailAddress,
        Password,
        PasswordConfirm,
        ForgetPassword,
        ForgetPasswordQustion,
        ForgetPasswordRecovery,
        NoAccount,
        HaveAccount,
        UserNameOrEmail,
        RegisterNewAccount,
        UserNameExists,
        EmailExists,
        UnknowError,
        EmailAddressExists,
    }
}
